export const trendingCases = [
    {
        id: 1,
        name: "SQUID Token",
        type: "Rugpull",
        risk: "Critical",
        riskScore: 98,
        totalAmount: "$3.3M",
        walletsInvolved: "12.5k",
        txVolume: "45.2k",
        blockchain: "BSC",
        description: "Play-to-earn game token that prevented selling, developers vanished with funds",
    },
    {
        id: 2,
        name: "SafeMoon V2",
        type: "Pump & Dump",
        risk: "High",
        riskScore: 87,
        totalAmount: "$1.2M",
        walletsInvolved: "8.3k",
        txVolume: "32.1k",
        blockchain: "BSC",
        description: "Coordinated pump and dump scheme targeting retail investors",
    },
    {
        id: 3,
        name: "Tornado Cash",
        type: "Money Laundering",
        risk: "High",
        riskScore: 92,
        totalAmount: "$100M+",
        walletsInvolved: "50k+",
        txVolume: "200k+",
        blockchain: "Ethereum",
        description: "Cryptocurrency mixer used for laundering stolen funds",
    },
    {
        id: 4,
        name: "Solana Monkey Business",
        type: "NFT Scam",
        risk: "Medium",
        riskScore: 65,
        totalAmount: "$500k",
        walletsInvolved: "2.1k",
        txVolume: "5.8k",
        blockchain: "Solana",
        description: "Fake NFT collection with plagiarized artwork",
    },
    {
        id: 5,
        name: "Tron Supernode",
        type: "Phishing",
        risk: "High",
        riskScore: 78,
        totalAmount: "$2M",
        walletsInvolved: "5.6k",
        txVolume: "18.9k",
        blockchain: "Tron",
        description: "Phishing campaign targeting Tron wallet users",
    },
    {
        id: 6,
        name: "AnubisDAO",
        type: "Rugpull",
        risk: "Critical",
        riskScore: 95,
        totalAmount: "$60M",
        walletsInvolved: "15k",
        txVolume: "25k",
        blockchain: "Ethereum",
        description: "DeFi protocol rugpull within 24 hours of launch",
    },
]
